terrain_simplification/topic_elevation_map:         /elevation_mapping_lidar/elevation_map
terrain_simplification/topic_robot_state:           /icp_odometry/corrected_pose
terrain_simplification/topic_map_simplified:        /terrain_simplification/map_simplified

terrain_simplification/gridmap_size_x:              8.0
terrain_simplification/gridmap_size_y:              8.0
terrain_simplification/h_nominal:                   0.53
terrain_simplification/map_res_scaling:             1.0
terrain_simplification/map_resolution:              0.02 #0.04 # 0.02

terrain_simplification/erode_radius:                0.11
terrain_simplification/traversability_threshold:    0.7
terrain_simplification/verbose_timer:               true
terrain_simplification/filter_chain_parameter_name: grid_map_filters
